/**
 * Banks data — country list (ISO 3166-1 alpha-2) and curated bank lists per
 * country.  This is a snapshot intended for picker UX — not an authoritative
 * registry. Banks are listed for the most common destinations; for countries
 * without an explicit list the picker falls back to free-text entry.
 *
 * Add or correct entries as needed.  Keep the file pure data, no runtime
 * imports.
 */

export interface Country {
  code: string;   // ISO 3166-1 alpha-2 (e.g. "ZA")
  name: string;   // Display name
  flag: string;   // Emoji flag
  dialCode?: string;
}

export interface Bank {
  /** Stable machine key, lowercase-kebab; safe for analytics / dedup */
  key: string;
  /** Display name */
  name: string;
  /** Short common abbreviation (optional) */
  short?: string;
}

// ── Full ISO country list ───────────────────────────────────────────────────
// Source: ISO 3166-1 alpha-2.  Flag emojis are the regional-indicator pair.

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan',            flag: '🇦🇫', dialCode: '+93'  },
  { code: 'AX', name: 'Åland Islands',          flag: '🇦🇽', dialCode: '+358' },
  { code: 'AL', name: 'Albania',                flag: '🇦🇱', dialCode: '+355' },
  { code: 'DZ', name: 'Algeria',                flag: '🇩🇿', dialCode: '+213' },
  { code: 'AS', name: 'American Samoa',         flag: '🇦🇸', dialCode: '+1684' },
  { code: 'AD', name: 'Andorra',                flag: '🇦🇩', dialCode: '+376' },
  { code: 'AO', name: 'Angola',                 flag: '🇦🇴', dialCode: '+244' },
  { code: 'AI', name: 'Anguilla',               flag: '🇦🇮', dialCode: '+1264' },
  { code: 'AQ', name: 'Antarctica',             flag: '🇦🇶' },
  { code: 'AG', name: 'Antigua & Barbuda',      flag: '🇦🇬', dialCode: '+1268' },
  { code: 'AR', name: 'Argentina',              flag: '🇦🇷', dialCode: '+54'  },
  { code: 'AM', name: 'Armenia',                flag: '🇦🇲', dialCode: '+374' },
  { code: 'AW', name: 'Aruba',                  flag: '🇦🇼', dialCode: '+297' },
  { code: 'AU', name: 'Australia',              flag: '🇦🇺', dialCode: '+61'  },
  { code: 'AT', name: 'Austria',                flag: '🇦🇹', dialCode: '+43'  },
  { code: 'AZ', name: 'Azerbaijan',             flag: '🇦🇿', dialCode: '+994' },
  { code: 'BS', name: 'Bahamas',                flag: '🇧🇸', dialCode: '+1242' },
  { code: 'BH', name: 'Bahrain',                flag: '🇧🇭', dialCode: '+973' },
  { code: 'BD', name: 'Bangladesh',             flag: '🇧🇩', dialCode: '+880' },
  { code: 'BB', name: 'Barbados',               flag: '🇧🇧', dialCode: '+1246' },
  { code: 'BY', name: 'Belarus',                flag: '🇧🇾', dialCode: '+375' },
  { code: 'BE', name: 'Belgium',                flag: '🇧🇪', dialCode: '+32'  },
  { code: 'BZ', name: 'Belize',                 flag: '🇧🇿', dialCode: '+501' },
  { code: 'BJ', name: 'Benin',                  flag: '🇧🇯', dialCode: '+229' },
  { code: 'BM', name: 'Bermuda',                flag: '🇧🇲', dialCode: '+1441' },
  { code: 'BT', name: 'Bhutan',                 flag: '🇧🇹', dialCode: '+975' },
  { code: 'BO', name: 'Bolivia',                flag: '🇧🇴', dialCode: '+591' },
  { code: 'BA', name: 'Bosnia & Herzegovina',   flag: '🇧🇦', dialCode: '+387' },
  { code: 'BW', name: 'Botswana',               flag: '🇧🇼', dialCode: '+267' },
  { code: 'BR', name: 'Brazil',                 flag: '🇧🇷', dialCode: '+55'  },
  { code: 'IO', name: 'British Indian Ocean Territory', flag: '🇮🇴', dialCode: '+246' },
  { code: 'VG', name: 'British Virgin Islands', flag: '🇻🇬', dialCode: '+1284' },
  { code: 'BN', name: 'Brunei',                 flag: '🇧🇳', dialCode: '+673' },
  { code: 'BG', name: 'Bulgaria',               flag: '🇧🇬', dialCode: '+359' },
  { code: 'BF', name: 'Burkina Faso',           flag: '🇧🇫', dialCode: '+226' },
  { code: 'BI', name: 'Burundi',                flag: '🇧🇮', dialCode: '+257' },
  { code: 'KH', name: 'Cambodia',               flag: '🇰🇭', dialCode: '+855' },
  { code: 'CM', name: 'Cameroon',               flag: '🇨🇲', dialCode: '+237' },
  { code: 'CA', name: 'Canada',                 flag: '🇨🇦', dialCode: '+1'   },
  { code: 'CV', name: 'Cape Verde',             flag: '🇨🇻', dialCode: '+238' },
  { code: 'BQ', name: 'Caribbean Netherlands',  flag: '🇧🇶', dialCode: '+599' },
  { code: 'KY', name: 'Cayman Islands',         flag: '🇰🇾', dialCode: '+1345' },
  { code: 'CF', name: 'Central African Republic', flag: '🇨🇫', dialCode: '+236' },
  { code: 'TD', name: 'Chad',                   flag: '🇹🇩', dialCode: '+235' },
  { code: 'CL', name: 'Chile',                  flag: '🇨🇱', dialCode: '+56'  },
  { code: 'CN', name: 'China',                  flag: '🇨🇳', dialCode: '+86'  },
  { code: 'CX', name: 'Christmas Island',       flag: '🇨🇽', dialCode: '+61'  },
  { code: 'CC', name: 'Cocos (Keeling) Islands', flag: '🇨🇨', dialCode: '+61'  },
  { code: 'CO', name: 'Colombia',               flag: '🇨🇴', dialCode: '+57'  },
  { code: 'KM', name: 'Comoros',                flag: '🇰🇲', dialCode: '+269' },
  { code: 'CG', name: 'Congo - Brazzaville',    flag: '🇨🇬', dialCode: '+242' },
  { code: 'CD', name: 'Congo - Kinshasa',       flag: '🇨🇩', dialCode: '+243' },
  { code: 'CK', name: 'Cook Islands',           flag: '🇨🇰', dialCode: '+682' },
  { code: 'CR', name: 'Costa Rica',             flag: '🇨🇷', dialCode: '+506' },
  { code: 'CI', name: 'Côte d’Ivoire',          flag: '🇨🇮', dialCode: '+225' },
  { code: 'HR', name: 'Croatia',                flag: '🇭🇷', dialCode: '+385' },
  { code: 'CU', name: 'Cuba',                   flag: '🇨🇺', dialCode: '+53'  },
  { code: 'CW', name: 'Curaçao',                flag: '🇨🇼', dialCode: '+599' },
  { code: 'CY', name: 'Cyprus',                 flag: '🇨🇾', dialCode: '+357' },
  { code: 'CZ', name: 'Czechia',                flag: '🇨🇿', dialCode: '+420' },
  { code: 'DK', name: 'Denmark',                flag: '🇩🇰', dialCode: '+45'  },
  { code: 'DJ', name: 'Djibouti',               flag: '🇩🇯', dialCode: '+253' },
  { code: 'DM', name: 'Dominica',               flag: '🇩🇲', dialCode: '+1767' },
  { code: 'DO', name: 'Dominican Republic',     flag: '🇩🇴', dialCode: '+1809' },
  { code: 'EC', name: 'Ecuador',                flag: '🇪🇨', dialCode: '+593' },
  { code: 'EG', name: 'Egypt',                  flag: '🇪🇬', dialCode: '+20'  },
  { code: 'SV', name: 'El Salvador',            flag: '🇸🇻', dialCode: '+503' },
  { code: 'GQ', name: 'Equatorial Guinea',      flag: '🇬🇶', dialCode: '+240' },
  { code: 'ER', name: 'Eritrea',                flag: '🇪🇷', dialCode: '+291' },
  { code: 'EE', name: 'Estonia',                flag: '🇪🇪', dialCode: '+372' },
  { code: 'SZ', name: 'Eswatini',               flag: '🇸🇿', dialCode: '+268' },
  { code: 'ET', name: 'Ethiopia',               flag: '🇪🇹', dialCode: '+251' },
  { code: 'FK', name: 'Falkland Islands',       flag: '🇫🇰', dialCode: '+500' },
  { code: 'FO', name: 'Faroe Islands',          flag: '🇫🇴', dialCode: '+298' },
  { code: 'FJ', name: 'Fiji',                   flag: '🇫🇯', dialCode: '+679' },
  { code: 'FI', name: 'Finland',                flag: '🇫🇮', dialCode: '+358' },
  { code: 'FR', name: 'France',                 flag: '🇫🇷', dialCode: '+33'  },
  { code: 'GF', name: 'French Guiana',          flag: '🇬🇫', dialCode: '+594' },
  { code: 'PF', name: 'French Polynesia',       flag: '🇵🇫', dialCode: '+689' },
  { code: 'GA', name: 'Gabon',                  flag: '🇬🇦', dialCode: '+241' },
  { code: 'GM', name: 'Gambia',                 flag: '🇬🇲', dialCode: '+220' },
  { code: 'GE', name: 'Georgia',                flag: '🇬🇪', dialCode: '+995' },
  { code: 'DE', name: 'Germany',                flag: '🇩🇪', dialCode: '+49'  },
  { code: 'GH', name: 'Ghana',                  flag: '🇬🇭', dialCode: '+233' },
  { code: 'GI', name: 'Gibraltar',              flag: '🇬🇮', dialCode: '+350' },
  { code: 'GR', name: 'Greece',                 flag: '🇬🇷', dialCode: '+30'  },
  { code: 'GL', name: 'Greenland',              flag: '🇬🇱', dialCode: '+299' },
  { code: 'GD', name: 'Grenada',                flag: '🇬🇩', dialCode: '+1473' },
  { code: 'GP', name: 'Guadeloupe',             flag: '🇬🇵', dialCode: '+590' },
  { code: 'GU', name: 'Guam',                   flag: '🇬🇺', dialCode: '+1671' },
  { code: 'GT', name: 'Guatemala',              flag: '🇬🇹', dialCode: '+502' },
  { code: 'GG', name: 'Guernsey',               flag: '🇬🇬', dialCode: '+44'  },
  { code: 'GN', name: 'Guinea',                 flag: '🇬🇳', dialCode: '+224' },
  { code: 'GW', name: 'Guinea-Bissau',          flag: '🇬🇼', dialCode: '+245' },
  { code: 'GY', name: 'Guyana',                 flag: '🇬🇾', dialCode: '+592' },
  { code: 'HT', name: 'Haiti',                  flag: '🇭🇹', dialCode: '+509' },
  { code: 'HN', name: 'Honduras',               flag: '🇭🇳', dialCode: '+504' },
  { code: 'HK', name: 'Hong Kong SAR China',    flag: '🇭🇰', dialCode: '+852' },
  { code: 'HU', name: 'Hungary',                flag: '🇭🇺', dialCode: '+36'  },
  { code: 'IS', name: 'Iceland',                flag: '🇮🇸', dialCode: '+354' },
  { code: 'IN', name: 'India',                  flag: '🇮🇳', dialCode: '+91'  },
  { code: 'ID', name: 'Indonesia',              flag: '🇮🇩', dialCode: '+62'  },
  { code: 'IR', name: 'Iran',                   flag: '🇮🇷', dialCode: '+98'  },
  { code: 'IQ', name: 'Iraq',                   flag: '🇮🇶', dialCode: '+964' },
  { code: 'IE', name: 'Ireland',                flag: '🇮🇪', dialCode: '+353' },
  { code: 'IM', name: 'Isle of Man',            flag: '🇮🇲', dialCode: '+44'  },
  { code: 'IL', name: 'Israel',                 flag: '🇮🇱', dialCode: '+972' },
  { code: 'IT', name: 'Italy',                  flag: '🇮🇹', dialCode: '+39'  },
  { code: 'JM', name: 'Jamaica',                flag: '🇯🇲', dialCode: '+1876' },
  { code: 'JP', name: 'Japan',                  flag: '🇯🇵', dialCode: '+81'  },
  { code: 'JE', name: 'Jersey',                 flag: '🇯🇪', dialCode: '+44'  },
  { code: 'JO', name: 'Jordan',                 flag: '🇯🇴', dialCode: '+962' },
  { code: 'KZ', name: 'Kazakhstan',             flag: '🇰🇿', dialCode: '+7'   },
  { code: 'KE', name: 'Kenya',                  flag: '🇰🇪', dialCode: '+254' },
  { code: 'KI', name: 'Kiribati',               flag: '🇰🇮', dialCode: '+686' },
  { code: 'KW', name: 'Kuwait',                 flag: '🇰🇼', dialCode: '+965' },
  { code: 'KG', name: 'Kyrgyzstan',             flag: '🇰🇬', dialCode: '+996' },
  { code: 'LA', name: 'Laos',                   flag: '🇱🇦', dialCode: '+856' },
  { code: 'LV', name: 'Latvia',                 flag: '🇱🇻', dialCode: '+371' },
  { code: 'LB', name: 'Lebanon',                flag: '🇱🇧', dialCode: '+961' },
  { code: 'LS', name: 'Lesotho',                flag: '🇱🇸', dialCode: '+266' },
  { code: 'LR', name: 'Liberia',                flag: '🇱🇷', dialCode: '+231' },
  { code: 'LY', name: 'Libya',                  flag: '🇱🇾', dialCode: '+218' },
  { code: 'LI', name: 'Liechtenstein',          flag: '🇱🇮', dialCode: '+423' },
  { code: 'LT', name: 'Lithuania',              flag: '🇱🇹', dialCode: '+370' },
  { code: 'LU', name: 'Luxembourg',             flag: '🇱🇺', dialCode: '+352' },
  { code: 'MO', name: 'Macao SAR China',        flag: '🇲🇴', dialCode: '+853' },
  { code: 'MG', name: 'Madagascar',             flag: '🇲🇬', dialCode: '+261' },
  { code: 'MW', name: 'Malawi',                 flag: '🇲🇼', dialCode: '+265' },
  { code: 'MY', name: 'Malaysia',               flag: '🇲🇾', dialCode: '+60'  },
  { code: 'MV', name: 'Maldives',               flag: '🇲🇻', dialCode: '+960' },
  { code: 'ML', name: 'Mali',                   flag: '🇲🇱', dialCode: '+223' },
  { code: 'MT', name: 'Malta',                  flag: '🇲🇹', dialCode: '+356' },
  { code: 'MH', name: 'Marshall Islands',       flag: '🇲🇭', dialCode: '+692' },
  { code: 'MQ', name: 'Martinique',             flag: '🇲🇶', dialCode: '+596' },
  { code: 'MR', name: 'Mauritania',             flag: '🇲🇷', dialCode: '+222' },
  { code: 'MU', name: 'Mauritius',              flag: '🇲🇺', dialCode: '+230' },
  { code: 'YT', name: 'Mayotte',                flag: '🇾🇹', dialCode: '+262' },
  { code: 'MX', name: 'Mexico',                 flag: '🇲🇽', dialCode: '+52'  },
  { code: 'FM', name: 'Micronesia',             flag: '🇫🇲', dialCode: '+691' },
  { code: 'MD', name: 'Moldova',                flag: '🇲🇩', dialCode: '+373' },
  { code: 'MC', name: 'Monaco',                 flag: '🇲🇨', dialCode: '+377' },
  { code: 'MN', name: 'Mongolia',               flag: '🇲🇳', dialCode: '+976' },
  { code: 'ME', name: 'Montenegro',             flag: '🇲🇪', dialCode: '+382' },
  { code: 'MS', name: 'Montserrat',             flag: '🇲🇸', dialCode: '+1664' },
  { code: 'MA', name: 'Morocco',                flag: '🇲🇦', dialCode: '+212' },
  { code: 'MZ', name: 'Mozambique',             flag: '🇲🇿', dialCode: '+258' },
  { code: 'MM', name: 'Myanmar (Burma)',        flag: '🇲🇲', dialCode: '+95'  },
  { code: 'NA', name: 'Namibia',                flag: '🇳🇦', dialCode: '+264' },
  { code: 'NR', name: 'Nauru',                  flag: '🇳🇷', dialCode: '+674' },
  { code: 'NP', name: 'Nepal',                  flag: '🇳🇵', dialCode: '+977' },
  { code: 'NL', name: 'Netherlands',            flag: '🇳🇱', dialCode: '+31'  },
  { code: 'NC', name: 'New Caledonia',          flag: '🇳🇨', dialCode: '+687' },
  { code: 'NZ', name: 'New Zealand',            flag: '🇳🇿', dialCode: '+64'  },
  { code: 'NI', name: 'Nicaragua',              flag: '🇳🇮', dialCode: '+505' },
  { code: 'NE', name: 'Niger',                  flag: '🇳🇪', dialCode: '+227' },
  { code: 'NG', name: 'Nigeria',                flag: '🇳🇬', dialCode: '+234' },
  { code: 'NU', name: 'Niue',                   flag: '🇳🇺', dialCode: '+683' },
  { code: 'NF', name: 'Norfolk Island',         flag: '🇳🇫', dialCode: '+672' },
  { code: 'KP', name: 'North Korea',            flag: '🇰🇵', dialCode: '+850' },
  { code: 'MK', name: 'North Macedonia',        flag: '🇲🇰', dialCode: '+389' },
  { code: 'MP', name: 'Northern Mariana Islands', flag: '🇲🇵', dialCode: '+1670' },
  { code: 'NO', name: 'Norway',                 flag: '🇳🇴', dialCode: '+47'  },
  { code: 'OM', name: 'Oman',                   flag: '🇴🇲', dialCode: '+968' },
  { code: 'PK', name: 'Pakistan',               flag: '🇵🇰', dialCode: '+92'  },
  { code: 'PW', name: 'Palau',                  flag: '🇵🇼', dialCode: '+680' },
  { code: 'PS', name: 'Palestinian Territories', flag: '🇵🇸', dialCode: '+970' },
  { code: 'PA', name: 'Panama',                 flag: '🇵🇦', dialCode: '+507' },
  { code: 'PG', name: 'Papua New Guinea',       flag: '🇵🇬', dialCode: '+675' },
  { code: 'PY', name: 'Paraguay',               flag: '🇵🇾', dialCode: '+595' },
  { code: 'PE', name: 'Peru',                   flag: '🇵🇪', dialCode: '+51'  },
  { code: 'PH', name: 'Philippines',            flag: '🇵🇭', dialCode: '+63'  },
  { code: 'PN', name: 'Pitcairn Islands',       flag: '🇵🇳', dialCode: '+64'  },
  { code: 'PL', name: 'Poland',                 flag: '🇵🇱', dialCode: '+48'  },
  { code: 'PT', name: 'Portugal',               flag: '🇵🇹', dialCode: '+351' },
  { code: 'PR', name: 'Puerto Rico',            flag: '🇵🇷', dialCode: '+1787' },
  { code: 'QA', name: 'Qatar',                  flag: '🇶🇦', dialCode: '+974' },
  { code: 'RE', name: 'Réunion',                flag: '🇷🇪', dialCode: '+262' },
  { code: 'RO', name: 'Romania',                flag: '🇷🇴', dialCode: '+40'  },
  { code: 'RU', name: 'Russia',                 flag: '🇷🇺', dialCode: '+7'   },
  { code: 'RW', name: 'Rwanda',                 flag: '🇷🇼', dialCode: '+250' },
  { code: 'WS', name: 'Samoa',                  flag: '🇼🇸', dialCode: '+685' },
  { code: 'SM', name: 'San Marino',             flag: '🇸🇲', dialCode: '+378' },
  { code: 'ST', name: 'São Tomé & Príncipe',    flag: '🇸🇹', dialCode: '+239' },
  { code: 'SA', name: 'Saudi Arabia',           flag: '🇸🇦', dialCode: '+966' },
  { code: 'SN', name: 'Senegal',                flag: '🇸🇳', dialCode: '+221' },
  { code: 'RS', name: 'Serbia',                 flag: '🇷🇸', dialCode: '+381' },
  { code: 'SC', name: 'Seychelles',             flag: '🇸🇨', dialCode: '+248' },
  { code: 'SL', name: 'Sierra Leone',           flag: '🇸🇱', dialCode: '+232' },
  { code: 'SG', name: 'Singapore',              flag: '🇸🇬', dialCode: '+65'  },
  { code: 'SX', name: 'Sint Maarten',           flag: '🇸🇽', dialCode: '+1721' },
  { code: 'SK', name: 'Slovakia',               flag: '🇸🇰', dialCode: '+421' },
  { code: 'SI', name: 'Slovenia',               flag: '🇸🇮', dialCode: '+386' },
  { code: 'SB', name: 'Solomon Islands',        flag: '🇸🇧', dialCode: '+677' },
  { code: 'SO', name: 'Somalia',                flag: '🇸🇴', dialCode: '+252' },
  { code: 'ZA', name: 'South Africa',           flag: '🇿🇦', dialCode: '+27'  },
  { code: 'GS', name: 'South Georgia & South Sandwich Islands', flag: '🇬🇸' },
  { code: 'KR', name: 'South Korea',            flag: '🇰🇷', dialCode: '+82'  },
  { code: 'SS', name: 'South Sudan',            flag: '🇸🇸', dialCode: '+211' },
  { code: 'ES', name: 'Spain',                  flag: '🇪🇸', dialCode: '+34'  },
  { code: 'LK', name: 'Sri Lanka',              flag: '🇱🇰', dialCode: '+94'  },
  { code: 'BL', name: 'St. Barthélemy',         flag: '🇧🇱', dialCode: '+590' },
  { code: 'SH', name: 'St. Helena',             flag: '🇸🇭', dialCode: '+290' },
  { code: 'KN', name: 'St. Kitts & Nevis',      flag: '🇰🇳', dialCode: '+1869' },
  { code: 'LC', name: 'St. Lucia',              flag: '🇱🇨', dialCode: '+1758' },
  { code: 'MF', name: 'St. Martin',             flag: '🇲🇫', dialCode: '+590' },
  { code: 'PM', name: 'St. Pierre & Miquelon',  flag: '🇵🇲', dialCode: '+508' },
  { code: 'VC', name: 'St. Vincent & Grenadines', flag: '🇻🇨', dialCode: '+1784' },
  { code: 'SD', name: 'Sudan',                  flag: '🇸🇩', dialCode: '+249' },
  { code: 'SR', name: 'Suriname',               flag: '🇸🇷', dialCode: '+597' },
  { code: 'SJ', name: 'Svalbard & Jan Mayen',   flag: '🇸🇯', dialCode: '+47'  },
  { code: 'SE', name: 'Sweden',                 flag: '🇸🇪', dialCode: '+46'  },
  { code: 'CH', name: 'Switzerland',            flag: '🇨🇭', dialCode: '+41'  },
  { code: 'SY', name: 'Syria',                  flag: '🇸🇾', dialCode: '+963' },
  { code: 'TW', name: 'Taiwan',                 flag: '🇹🇼', dialCode: '+886' },
  { code: 'TJ', name: 'Tajikistan',             flag: '🇹🇯', dialCode: '+992' },
  { code: 'TZ', name: 'Tanzania',               flag: '🇹🇿', dialCode: '+255' },
  { code: 'TH', name: 'Thailand',               flag: '🇹🇭', dialCode: '+66'  },
  { code: 'TL', name: 'Timor-Leste',            flag: '🇹🇱', dialCode: '+670' },
  { code: 'TG', name: 'Togo',                   flag: '🇹🇬', dialCode: '+228' },
  { code: 'TK', name: 'Tokelau',                flag: '🇹🇰', dialCode: '+690' },
  { code: 'TO', name: 'Tonga',                  flag: '🇹🇴', dialCode: '+676' },
  { code: 'TT', name: 'Trinidad & Tobago',      flag: '🇹🇹', dialCode: '+1868' },
  { code: 'TN', name: 'Tunisia',                flag: '🇹🇳', dialCode: '+216' },
  { code: 'TR', name: 'Turkey',                 flag: '🇹🇷', dialCode: '+90'  },
  { code: 'TM', name: 'Turkmenistan',           flag: '🇹🇲', dialCode: '+993' },
  { code: 'TC', name: 'Turks & Caicos Islands', flag: '🇹🇨', dialCode: '+1649' },
  { code: 'TV', name: 'Tuvalu',                 flag: '🇹🇻', dialCode: '+688' },
  { code: 'UM', name: 'U.S. Outlying Islands',  flag: '🇺🇲' },
  { code: 'VI', name: 'U.S. Virgin Islands',    flag: '🇻🇮', dialCode: '+1340' },
  { code: 'UG', name: 'Uganda',                 flag: '🇺🇬', dialCode: '+256' },
  { code: 'UA', name: 'Ukraine',                flag: '🇺🇦', dialCode: '+380' },
  { code: 'AE', name: 'United Arab Emirates',   flag: '🇦🇪', dialCode: '+971' },
  { code: 'GB', name: 'United Kingdom',         flag: '🇬🇧', dialCode: '+44'  },
  { code: 'US', name: 'United States',          flag: '🇺🇸', dialCode: '+1'   },
  { code: 'UY', name: 'Uruguay',                flag: '🇺🇾', dialCode: '+598' },
  { code: 'UZ', name: 'Uzbekistan',             flag: '🇺🇿', dialCode: '+998' },
  { code: 'VU', name: 'Vanuatu',                flag: '🇻🇺', dialCode: '+678' },
  { code: 'VA', name: 'Vatican City',           flag: '🇻🇦', dialCode: '+39'  },
  { code: 'VE', name: 'Venezuela',              flag: '🇻🇪', dialCode: '+58'  },
  { code: 'VN', name: 'Vietnam',                flag: '🇻🇳', dialCode: '+84'  },
  { code: 'WF', name: 'Wallis & Futuna',        flag: '🇼🇫', dialCode: '+681' },
  { code: 'EH', name: 'Western Sahara',         flag: '🇪🇭', dialCode: '+212' },
  { code: 'YE', name: 'Yemen',                  flag: '🇾🇪', dialCode: '+967' },
  { code: 'ZM', name: 'Zambia',                 flag: '🇿🇲', dialCode: '+260' },
  { code: 'ZW', name: 'Zimbabwe',               flag: '🇿🇼', dialCode: '+263' },
];

// ── Curated bank lists per country ───────────────────────────────────────────
// Sourced from public regulator listings. Order roughly by retail-banking share.
// Countries omitted from this map fall back to free-text entry in the UI.

export const BANKS_BY_COUNTRY: Record<string, Bank[]> = {
  ZA: [
    { key: 'fnb',           name: 'First National Bank',    short: 'FNB' },
    { key: 'standard-bank', name: 'Standard Bank',          short: 'SBSA' },
    { key: 'absa',          name: 'Absa Bank' },
    { key: 'nedbank',       name: 'Nedbank' },
    { key: 'capitec',       name: 'Capitec Bank' },
    { key: 'african-bank',  name: 'African Bank' },
    { key: 'investec',      name: 'Investec' },
    { key: 'discovery',     name: 'Discovery Bank' },
    { key: 'tymebank',      name: 'TymeBank' },
    { key: 'bidvest',       name: 'Bidvest Bank' },
    { key: 'sasfin',        name: 'Sasfin Bank' },
    { key: 'postbank',      name: 'Postbank' },
    { key: 'bank-zero',     name: 'Bank Zero' },
    { key: 'grindrod',      name: 'Grindrod Bank' },
    { key: 'mercantile',    name: 'Mercantile Bank' },
    { key: 'hbz',           name: 'HBZ Bank' },
    { key: 'access-bank',   name: 'Access Bank South Africa' },
  ],
  US: [
    { key: 'chase',          name: 'JPMorgan Chase' },
    { key: 'boa',            name: 'Bank of America' },
    { key: 'wells-fargo',    name: 'Wells Fargo' },
    { key: 'citi',           name: 'Citibank' },
    { key: 'us-bank',        name: 'U.S. Bank' },
    { key: 'pnc',            name: 'PNC Bank' },
    { key: 'truist',         name: 'Truist Bank' },
    { key: 'capital-one',    name: 'Capital One' },
    { key: 'td-bank',        name: 'TD Bank' },
    { key: 'goldman',        name: 'Goldman Sachs' },
    { key: 'morgan-stanley', name: 'Morgan Stanley' },
    { key: 'hsbc-usa',       name: 'HSBC USA' },
    { key: 'ally',           name: 'Ally Bank' },
    { key: 'discover',       name: 'Discover Bank' },
    { key: 'navy-federal',   name: 'Navy Federal Credit Union' },
    { key: 'charles-schwab', name: 'Charles Schwab Bank' },
    { key: 'american-express', name: 'American Express Bank' },
    { key: 'chime',          name: 'Chime' },
    { key: 'sofi',           name: 'SoFi Bank' },
    { key: 'first-republic', name: 'First Republic Bank' },
  ],
  GB: [
    { key: 'hsbc',          name: 'HSBC UK' },
    { key: 'barclays',      name: 'Barclays' },
    { key: 'lloyds',        name: 'Lloyds Bank' },
    { key: 'natwest',       name: 'NatWest' },
    { key: 'santander-uk',  name: 'Santander UK' },
    { key: 'halifax',       name: 'Halifax' },
    { key: 'tsb',           name: 'TSB Bank' },
    { key: 'monzo',         name: 'Monzo' },
    { key: 'starling',      name: 'Starling Bank' },
    { key: 'revolut-gb',    name: 'Revolut' },
    { key: 'nationwide',    name: 'Nationwide Building Society' },
    { key: 'bank-of-scotland', name: 'Bank of Scotland' },
    { key: 'rbs',           name: 'Royal Bank of Scotland' },
    { key: 'first-direct',  name: 'First Direct' },
    { key: 'metro-bank',    name: 'Metro Bank' },
    { key: 'co-operative-bank', name: 'The Co-operative Bank' },
  ],
  CA: [
    { key: 'rbc',     name: 'Royal Bank of Canada' },
    { key: 'td-ca',   name: 'TD Canada Trust' },
    { key: 'scotia',  name: 'Scotiabank' },
    { key: 'bmo',     name: 'BMO Bank of Montreal' },
    { key: 'cibc',    name: 'CIBC' },
    { key: 'national-bank', name: 'National Bank of Canada' },
    { key: 'desjardins', name: 'Desjardins' },
    { key: 'tangerine', name: 'Tangerine' },
    { key: 'hsbc-ca',  name: 'HSBC Canada' },
    { key: 'simplii',  name: 'Simplii Financial' },
    { key: 'eq-bank',  name: 'EQ Bank' },
    { key: 'laurentian', name: 'Laurentian Bank' },
  ],
  NG: [
    { key: 'gtb',       name: 'Guaranty Trust Bank' },
    { key: 'zenith',    name: 'Zenith Bank' },
    { key: 'first-bank', name: 'First Bank of Nigeria' },
    { key: 'access',    name: 'Access Bank' },
    { key: 'uba',       name: 'United Bank for Africa' },
    { key: 'fcmb',      name: 'FCMB' },
    { key: 'stanbic-ng', name: 'Stanbic IBTC Bank' },
    { key: 'ecobank-ng', name: 'Ecobank Nigeria' },
    { key: 'fidelity',  name: 'Fidelity Bank' },
    { key: 'union',     name: 'Union Bank of Nigeria' },
    { key: 'wema',      name: 'Wema Bank' },
    { key: 'sterling',  name: 'Sterling Bank' },
    { key: 'polaris',   name: 'Polaris Bank' },
    { key: 'kuda',      name: 'Kuda Bank' },
    { key: 'opay',      name: 'OPay' },
    { key: 'palmpay',   name: 'PalmPay' },
    { key: 'providus',  name: 'Providus Bank' },
    { key: 'jaiz',      name: 'Jaiz Bank' },
  ],
  KE: [
    { key: 'kcb',           name: 'Kenya Commercial Bank' },
    { key: 'equity',        name: 'Equity Bank' },
    { key: 'coop',          name: 'Co-operative Bank of Kenya' },
    { key: 'absa-ke',       name: 'Absa Bank Kenya' },
    { key: 'stanchart-ke',  name: 'Standard Chartered Kenya' },
    { key: 'ncba',          name: 'NCBA Bank' },
    { key: 'dtb',           name: 'Diamond Trust Bank' },
    { key: 'i&m',           name: 'I&M Bank' },
    { key: 'family',        name: 'Family Bank' },
    { key: 'stanbic-ke',    name: 'Stanbic Bank Kenya' },
    { key: 'mpesa-mshwari', name: 'M-Shwari / M-Pesa' },
  ],
  GH: [
    { key: 'gcb',         name: 'GCB Bank' },
    { key: 'ecobank-gh',  name: 'Ecobank Ghana' },
    { key: 'absa-gh',     name: 'Absa Bank Ghana' },
    { key: 'stanbic-gh',  name: 'Stanbic Bank Ghana' },
    { key: 'fidelity-gh', name: 'Fidelity Bank Ghana' },
    { key: 'cal-bank',    name: 'CalBank' },
    { key: 'agric-dev-bank', name: 'Agricultural Development Bank' },
    { key: 'zenith-gh',   name: 'Zenith Bank Ghana' },
    { key: 'access-gh',   name: 'Access Bank Ghana' },
    { key: 'uba-gh',      name: 'UBA Ghana' },
  ],
  EG: [
    { key: 'nbe',           name: 'National Bank of Egypt' },
    { key: 'banque-misr',   name: 'Banque Misr' },
    { key: 'cib',           name: 'Commercial International Bank' },
    { key: 'banque-du-caire', name: 'Banque du Caire' },
    { key: 'qnb-alahli',    name: 'QNB Al Ahli' },
    { key: 'aub',           name: 'Arab African International Bank' },
    { key: 'hsbc-eg',       name: 'HSBC Egypt' },
    { key: 'credit-agricole-eg', name: 'Crédit Agricole Egypt' },
  ],
  AU: [
    { key: 'commonwealth',  name: 'Commonwealth Bank' },
    { key: 'westpac',       name: 'Westpac' },
    { key: 'anz',           name: 'ANZ' },
    { key: 'nab',           name: 'National Australia Bank' },
    { key: 'macquarie',     name: 'Macquarie Bank' },
    { key: 'bendigo',       name: 'Bendigo Bank' },
    { key: 'suncorp',       name: 'Suncorp Bank' },
    { key: 'ing-au',        name: 'ING Australia' },
    { key: 'me-bank',       name: 'ME Bank' },
    { key: 'ubank',         name: 'UBank' },
  ],
  NZ: [
    { key: 'anz-nz',     name: 'ANZ Bank New Zealand' },
    { key: 'asb',        name: 'ASB Bank' },
    { key: 'bnz',        name: 'Bank of New Zealand' },
    { key: 'westpac-nz', name: 'Westpac New Zealand' },
    { key: 'kiwibank',   name: 'Kiwibank' },
    { key: 'tsb-nz',     name: 'TSB Bank' },
    { key: 'co-op-nz',   name: 'The Co-operative Bank' },
  ],
  IN: [
    { key: 'sbi',          name: 'State Bank of India' },
    { key: 'hdfc',         name: 'HDFC Bank' },
    { key: 'icici',        name: 'ICICI Bank' },
    { key: 'axis',         name: 'Axis Bank' },
    { key: 'kotak',        name: 'Kotak Mahindra Bank' },
    { key: 'pnb',          name: 'Punjab National Bank' },
    { key: 'bob',          name: 'Bank of Baroda' },
    { key: 'canara',       name: 'Canara Bank' },
    { key: 'union-india',  name: 'Union Bank of India' },
    { key: 'indusind',     name: 'IndusInd Bank' },
    { key: 'idfc-first',   name: 'IDFC First Bank' },
    { key: 'yes',          name: 'Yes Bank' },
    { key: 'rbl',          name: 'RBL Bank' },
    { key: 'bandhan',      name: 'Bandhan Bank' },
    { key: 'federal-india', name: 'Federal Bank' },
    { key: 'paytm',        name: 'Paytm Payments Bank' },
  ],
  DE: [
    { key: 'deutsche-bank', name: 'Deutsche Bank' },
    { key: 'commerzbank',   name: 'Commerzbank' },
    { key: 'sparkasse',     name: 'Sparkasse' },
    { key: 'dz-bank',       name: 'DZ Bank' },
    { key: 'kfw',           name: 'KfW' },
    { key: 'ing-de',        name: 'ING Deutschland' },
    { key: 'postbank',      name: 'Postbank' },
    { key: 'unicredit-de',  name: 'UniCredit Bank (HVB)' },
    { key: 'n26',           name: 'N26' },
    { key: 'dkb',           name: 'DKB' },
  ],
  FR: [
    { key: 'bnp',           name: 'BNP Paribas' },
    { key: 'credit-agricole', name: 'Crédit Agricole' },
    { key: 'societe-generale', name: 'Société Générale' },
    { key: 'banque-postale', name: 'La Banque Postale' },
    { key: 'cic',           name: 'CIC' },
    { key: 'credit-mutuel', name: 'Crédit Mutuel' },
    { key: 'bpce',          name: 'BPCE / Caisse d’Épargne' },
    { key: 'lcl',           name: 'LCL' },
    { key: 'boursorama',    name: 'BoursoBank (Boursorama)' },
    { key: 'revolut-fr',    name: 'Revolut' },
  ],
  ES: [
    { key: 'santander-es', name: 'Banco Santander' },
    { key: 'bbva',         name: 'BBVA' },
    { key: 'caixabank',    name: 'CaixaBank' },
    { key: 'banco-sabadell', name: 'Banco Sabadell' },
    { key: 'bankinter',    name: 'Bankinter' },
    { key: 'ing-es',       name: 'ING España' },
    { key: 'unicaja',      name: 'Unicaja Banco' },
    { key: 'kutxabank',    name: 'Kutxabank' },
  ],
  IT: [
    { key: 'intesa',    name: 'Intesa Sanpaolo' },
    { key: 'unicredit-it', name: 'UniCredit' },
    { key: 'mediobanca', name: 'Mediobanca' },
    { key: 'monte-paschi', name: 'Banca Monte dei Paschi di Siena' },
    { key: 'bper',     name: 'BPER Banca' },
    { key: 'mediolanum', name: 'Banca Mediolanum' },
    { key: 'fineco',   name: 'Fineco Bank' },
  ],
  NL: [
    { key: 'abn-amro', name: 'ABN AMRO' },
    { key: 'ing-nl',   name: 'ING Bank' },
    { key: 'rabobank', name: 'Rabobank' },
    { key: 'sns',      name: 'SNS Bank' },
    { key: 'bunq',     name: 'bunq' },
    { key: 'triodos',  name: 'Triodos Bank' },
  ],
  BR: [
    { key: 'itau',       name: 'Itaú Unibanco' },
    { key: 'bradesco',   name: 'Bradesco' },
    { key: 'banco-do-brasil', name: 'Banco do Brasil' },
    { key: 'santander-br', name: 'Santander Brasil' },
    { key: 'caixa-econ',  name: 'Caixa Econômica Federal' },
    { key: 'nubank',     name: 'Nubank' },
    { key: 'inter',      name: 'Banco Inter' },
    { key: 'btg-pactual', name: 'BTG Pactual' },
    { key: 'safra',      name: 'Banco Safra' },
    { key: 'c6',         name: 'C6 Bank' },
  ],
  MX: [
    { key: 'bbva-mx',    name: 'BBVA México' },
    { key: 'banamex',    name: 'Citibanamex' },
    { key: 'santander-mx', name: 'Santander México' },
    { key: 'banorte',    name: 'Banorte' },
    { key: 'hsbc-mx',    name: 'HSBC México' },
    { key: 'scotia-mx',  name: 'Scotiabank México' },
    { key: 'inbursa',    name: 'Banco Inbursa' },
    { key: 'azteca',     name: 'Banco Azteca' },
  ],
  AR: [
    { key: 'banco-nacion', name: 'Banco de la Nación Argentina' },
    { key: 'galicia',      name: 'Banco Galicia' },
    { key: 'santander-ar', name: 'Santander Argentina' },
    { key: 'bbva-ar',      name: 'BBVA Argentina' },
    { key: 'macro',        name: 'Banco Macro' },
    { key: 'icbc-ar',      name: 'ICBC Argentina' },
    { key: 'mercado-pago', name: 'Mercado Pago' },
  ],
  JP: [
    { key: 'mufg',       name: 'MUFG Bank' },
    { key: 'smbc',       name: 'Sumitomo Mitsui Banking Corporation' },
    { key: 'mizuho',     name: 'Mizuho Bank' },
    { key: 'resona',     name: 'Resona Bank' },
    { key: 'japan-post', name: 'Japan Post Bank' },
    { key: 'rakuten-jp', name: 'Rakuten Bank' },
    { key: 'sony-jp',    name: 'Sony Bank' },
    { key: 'sbi-jp',     name: 'SBI Sumishin Net Bank' },
  ],
  CN: [
    { key: 'icbc',     name: 'Industrial and Commercial Bank of China' },
    { key: 'ccb',      name: 'China Construction Bank' },
    { key: 'abc',      name: 'Agricultural Bank of China' },
    { key: 'boc',      name: 'Bank of China' },
    { key: 'bocom',    name: 'Bank of Communications' },
    { key: 'cmb',      name: 'China Merchants Bank' },
    { key: 'cmbc',     name: 'China Minsheng Bank' },
    { key: 'spdb',     name: 'Shanghai Pudong Development Bank' },
    { key: 'ceb',      name: 'China Everbright Bank' },
    { key: 'wechat-pay', name: 'WeChat Pay' },
    { key: 'alipay',   name: 'Alipay' },
  ],
  KR: [
    { key: 'kb',         name: 'KB Kookmin Bank' },
    { key: 'shinhan',    name: 'Shinhan Bank' },
    { key: 'hana',       name: 'Hana Bank' },
    { key: 'woori',      name: 'Woori Bank' },
    { key: 'nh-nonghyup', name: 'NH NongHyup Bank' },
    { key: 'ibk',        name: 'Industrial Bank of Korea' },
    { key: 'kakao-bank', name: 'KakaoBank' },
    { key: 'toss-bank',  name: 'Toss Bank' },
  ],
  SG: [
    { key: 'dbs',        name: 'DBS Bank' },
    { key: 'uob',        name: 'UOB' },
    { key: 'ocbc',       name: 'OCBC Bank' },
    { key: 'stanchart-sg', name: 'Standard Chartered Singapore' },
    { key: 'hsbc-sg',    name: 'HSBC Singapore' },
    { key: 'citi-sg',    name: 'Citibank Singapore' },
    { key: 'maybank-sg', name: 'Maybank Singapore' },
    { key: 'trust',      name: 'Trust Bank' },
  ],
  AE: [
    { key: 'enbd',       name: 'Emirates NBD' },
    { key: 'fab',        name: 'First Abu Dhabi Bank' },
    { key: 'adcb',       name: 'Abu Dhabi Commercial Bank' },
    { key: 'dib',        name: 'Dubai Islamic Bank' },
    { key: 'mashreq',    name: 'Mashreq Bank' },
    { key: 'rakbank',    name: 'RAK Bank' },
    { key: 'cbd',        name: 'Commercial Bank of Dubai' },
    { key: 'hsbc-ae',    name: 'HSBC UAE' },
    { key: 'liv',        name: 'Liv. by Emirates NBD' },
  ],
  SA: [
    { key: 'al-rajhi',     name: 'Al Rajhi Bank' },
    { key: 'snb',          name: 'Saudi National Bank' },
    { key: 'riyad-bank',   name: 'Riyad Bank' },
    { key: 'sabb',         name: 'Saudi British Bank (SABB)' },
    { key: 'alinma',       name: 'Alinma Bank' },
    { key: 'bsf',          name: 'Banque Saudi Fransi' },
    { key: 'bank-aljazira', name: 'Bank AlJazira' },
    { key: 'arab-national', name: 'Arab National Bank' },
  ],
  ID: [
    { key: 'bri',     name: 'Bank Rakyat Indonesia' },
    { key: 'mandiri', name: 'Bank Mandiri' },
    { key: 'bca',     name: 'Bank Central Asia' },
    { key: 'bni',     name: 'Bank Negara Indonesia' },
    { key: 'cimb-id', name: 'CIMB Niaga' },
    { key: 'permata', name: 'Bank Permata' },
    { key: 'danamon', name: 'Bank Danamon' },
    { key: 'jago',    name: 'Bank Jago' },
  ],
  PH: [
    { key: 'bdo',     name: 'BDO Unibank' },
    { key: 'metrobank', name: 'Metrobank' },
    { key: 'bpi',     name: 'Bank of the Philippine Islands' },
    { key: 'landbank', name: 'Land Bank of the Philippines' },
    { key: 'pnb-ph',  name: 'Philippine National Bank' },
    { key: 'security-bank', name: 'Security Bank' },
    { key: 'unionbank-ph', name: 'UnionBank of the Philippines' },
    { key: 'gcash',   name: 'GCash' },
    { key: 'maya',    name: 'Maya Bank' },
  ],
  TH: [
    { key: 'bbl',     name: 'Bangkok Bank' },
    { key: 'kbank',   name: 'Kasikornbank' },
    { key: 'scb-th',  name: 'Siam Commercial Bank' },
    { key: 'ktb',     name: 'Krungthai Bank' },
    { key: 'bay',     name: 'Krungsri (Bank of Ayudhya)' },
    { key: 'tmbthanachart', name: 'TMBThanachart Bank' },
    { key: 'uob-th',  name: 'UOB Thailand' },
  ],
  VN: [
    { key: 'vietcombank', name: 'Vietcombank' },
    { key: 'bidv',        name: 'BIDV' },
    { key: 'vietinbank',  name: 'VietinBank' },
    { key: 'agribank',    name: 'Agribank' },
    { key: 'tcb',         name: 'Techcombank' },
    { key: 'mb',          name: 'MB Bank' },
    { key: 'vpbank',      name: 'VPBank' },
    { key: 'acb',         name: 'Asia Commercial Bank' },
  ],
  TR: [
    { key: 'ziraat',       name: 'Ziraat Bankası' },
    { key: 'is-bankasi',   name: 'Türkiye İş Bankası' },
    { key: 'garanti-bbva', name: 'Garanti BBVA' },
    { key: 'akbank',       name: 'Akbank' },
    { key: 'yapi-kredi',   name: 'Yapı Kredi' },
    { key: 'denizbank',    name: 'DenizBank' },
    { key: 'finansbank',   name: 'QNB Finansbank' },
    { key: 'halkbank',     name: 'Halkbank' },
    { key: 'vakifbank',    name: 'VakıfBank' },
  ],
  RU: [
    { key: 'sberbank',    name: 'Sberbank' },
    { key: 'vtb',         name: 'VTB Bank' },
    { key: 'gazprombank', name: 'Gazprombank' },
    { key: 'alfa-bank',   name: 'Alfa-Bank' },
    { key: 'tinkoff',     name: 'Tinkoff Bank (T-Bank)' },
    { key: 'rosselkhozbank', name: 'Rosselkhozbank' },
    { key: 'otkritie',    name: 'Otkritie Bank' },
  ],
  CH: [
    { key: 'ubs',           name: 'UBS' },
    { key: 'raiffeisen-ch', name: 'Raiffeisen Switzerland' },
    { key: 'zkb',           name: 'Zürcher Kantonalbank' },
    { key: 'postfinance',   name: 'PostFinance' },
    { key: 'cembra',        name: 'Cembra Money Bank' },
    { key: 'revolut-ch',    name: 'Revolut' },
  ],
  SE: [
    { key: 'seb',      name: 'SEB' },
    { key: 'handelsbanken', name: 'Svenska Handelsbanken' },
    { key: 'swedbank', name: 'Swedbank' },
    { key: 'nordea-se', name: 'Nordea' },
    { key: 'danske-se', name: 'Danske Bank' },
  ],
  NO: [
    { key: 'dnb',           name: 'DNB' },
    { key: 'nordea-no',     name: 'Nordea Norge' },
    { key: 'sparebank-1',   name: 'SpareBank 1' },
    { key: 'sbanken',       name: 'Sbanken' },
  ],
  DK: [
    { key: 'danske-bank', name: 'Danske Bank' },
    { key: 'nordea-dk',   name: 'Nordea Danmark' },
    { key: 'jyske',       name: 'Jyske Bank' },
    { key: 'sydbank',     name: 'Sydbank' },
  ],
  FI: [
    { key: 'op-fi',       name: 'OP Financial Group' },
    { key: 'nordea-fi',   name: 'Nordea Finland' },
    { key: 'danske-fi',   name: 'Danske Bank Finland' },
    { key: 's-pankki',    name: 'S-Pankki' },
  ],
  IE: [
    { key: 'aib',  name: 'AIB' },
    { key: 'boi',  name: 'Bank of Ireland' },
    { key: 'ptsb', name: 'Permanent TSB' },
    { key: 'revolut-ie', name: 'Revolut Ireland' },
    { key: 'n26-ie', name: 'N26 Ireland' },
  ],
  PT: [
    { key: 'cgd',      name: 'Caixa Geral de Depósitos' },
    { key: 'bcp',      name: 'Millennium BCP' },
    { key: 'novobanco', name: 'Novo Banco' },
    { key: 'santander-pt', name: 'Santander Totta' },
    { key: 'bpi',      name: 'Banco BPI' },
    { key: 'montepio', name: 'Banco Montepio' },
  ],
  BE: [
    { key: 'bnp-paribas-fortis', name: 'BNP Paribas Fortis' },
    { key: 'kbc',  name: 'KBC Bank' },
    { key: 'belfius', name: 'Belfius' },
    { key: 'ing-be', name: 'ING België' },
  ],
  PL: [
    { key: 'pko-bp',  name: 'PKO Bank Polski' },
    { key: 'pekao',   name: 'Bank Pekao' },
    { key: 'santander-pl', name: 'Santander Bank Polska' },
    { key: 'mbank',   name: 'mBank' },
    { key: 'ing-pl',  name: 'ING Bank Śląski' },
    { key: 'millennium-pl', name: 'Bank Millennium' },
  ],
  RO: [
    { key: 'bcr',         name: 'Banca Comercială Română' },
    { key: 'brd',         name: 'BRD - Groupe Société Générale' },
    { key: 'banca-transilvania', name: 'Banca Transilvania' },
    { key: 'ing-ro',      name: 'ING Bank România' },
    { key: 'raiffeisen-ro', name: 'Raiffeisen Bank România' },
  ],
  GR: [
    { key: 'piraeus',     name: 'Piraeus Bank' },
    { key: 'national-greece', name: 'National Bank of Greece' },
    { key: 'eurobank',    name: 'Eurobank' },
    { key: 'alpha-bank',  name: 'Alpha Bank' },
  ],
  CZ: [
    { key: 'csob',     name: 'ČSOB' },
    { key: 'ceska-sporitelna', name: 'Česká spořitelna' },
    { key: 'kb-cz',    name: 'Komerční banka' },
    { key: 'air-bank', name: 'Air Bank' },
    { key: 'unicredit-cz', name: 'UniCredit Bank Czech' },
  ],
  HU: [
    { key: 'otp',         name: 'OTP Bank' },
    { key: 'k&h',         name: 'K&H Bank' },
    { key: 'erste-hu',    name: 'Erste Bank Hungary' },
    { key: 'mbh',         name: 'MBH Bank' },
  ],
  MA: [
    { key: 'attijariwafa', name: 'Attijariwafa Bank' },
    { key: 'bp',           name: 'Banque Populaire' },
    { key: 'bmce',         name: 'BMCE Bank of Africa' },
    { key: 'cih',          name: 'CIH Bank' },
    { key: 'sg-ma',        name: 'Société Générale Maroc' },
  ],
  TZ: [
    { key: 'crdb',     name: 'CRDB Bank' },
    { key: 'nmb',      name: 'NMB Bank' },
    { key: 'nbc',      name: 'National Bank of Commerce' },
    { key: 'stanbic-tz', name: 'Stanbic Bank Tanzania' },
    { key: 'absa-tz',  name: 'Absa Bank Tanzania' },
    { key: 'equity-tz', name: 'Equity Bank Tanzania' },
  ],
  UG: [
    { key: 'stanbic-ug', name: 'Stanbic Bank Uganda' },
    { key: 'centenary', name: 'Centenary Bank' },
    { key: 'absa-ug',   name: 'Absa Bank Uganda' },
    { key: 'dfcu',      name: 'Dfcu Bank' },
    { key: 'standard-chartered-ug', name: 'Standard Chartered Uganda' },
  ],
  RW: [
    { key: 'bk',      name: 'Bank of Kigali' },
    { key: 'i&m-rw',  name: 'I&M Bank Rwanda' },
    { key: 'equity-rw', name: 'Equity Bank Rwanda' },
    { key: 'gt-bank-rw', name: 'GT Bank Rwanda' },
    { key: 'access-rw', name: 'Access Bank Rwanda' },
  ],
  ZW: [
    { key: 'cbz',          name: 'CBZ Bank' },
    { key: 'stanbic-zw',   name: 'Stanbic Bank Zimbabwe' },
    { key: 'standard-chartered-zw', name: 'Standard Chartered Zimbabwe' },
    { key: 'nedbank-zw',   name: 'Nedbank Zimbabwe' },
    { key: 'ecocash',      name: 'EcoCash' },
  ],
  ZM: [
    { key: 'zanaco',      name: 'Zanaco' },
    { key: 'stanbic-zm',  name: 'Stanbic Bank Zambia' },
    { key: 'absa-zm',     name: 'Absa Bank Zambia' },
    { key: 'fnb-zm',      name: 'First National Bank Zambia' },
    { key: 'standard-chartered-zm', name: 'Standard Chartered Zambia' },
  ],
  BW: [
    { key: 'fnbb',        name: 'First National Bank of Botswana' },
    { key: 'absa-bw',     name: 'Absa Bank Botswana' },
    { key: 'standard-chartered-bw', name: 'Standard Chartered Botswana' },
    { key: 'stanbic-bw',  name: 'Stanbic Bank Botswana' },
  ],
  NA: [
    { key: 'bank-windhoek', name: 'Bank Windhoek' },
    { key: 'fnb-na',        name: 'FNB Namibia' },
    { key: 'standard-bank-na', name: 'Standard Bank Namibia' },
    { key: 'nedbank-na',    name: 'Nedbank Namibia' },
  ],
  MU: [
    { key: 'mcb',          name: 'Mauritius Commercial Bank' },
    { key: 'sbm',          name: 'State Bank of Mauritius' },
    { key: 'absa-mu',      name: 'Absa Bank Mauritius' },
    { key: 'mauritius-post', name: 'MauBank' },
  ],
};
