export interface KybDocumentRequirement {
  key: string;
  label: string;
  description: string;
  required: boolean;
  acceptedFormats: string[];
  maxSizeMb: number;
}

export interface KybBusinessInfoField {
  key: string;
  label: string;
  type: 'text' | 'number' | 'date' | 'select';
  required: boolean;
  placeholder?: string;
  hint?: string;
  options?: string[];
}

export interface CountryKybConfig {
  countryCode: string;
  countryName: string;
  currency: string;
  registrationAuthority: string;
  documents: KybDocumentRequirement[];
  businessInfoFields: KybBusinessInfoField[];
  notes?: string;
}

const PDF_IMG = ['pdf', 'jpg', 'jpeg', 'png'];
const MAX_MB = 10;

function doc(
  key: string,
  label: string,
  description: string,
  required = true,
): KybDocumentRequirement {
  return { key, label, description, required, acceptedFormats: PDF_IMG, maxSizeMb: MAX_MB };
}

function field(
  key: string,
  label: string,
  type: KybBusinessInfoField['type'],
  required = true,
  extra: Partial<KybBusinessInfoField> = {},
): KybBusinessInfoField {
  return { key, label, type, required, ...extra };
}

const COMMON_DOCS = {
  directorId: doc('director_id', 'Director / Beneficial Owner ID', 'Valid government-issued photo ID (passport or national ID) of each director or beneficial owner (≥25% stake).'),
  proofOfAddress: doc('proof_of_address', 'Proof of Business Address', 'Utility bill, bank statement, or lease agreement dated within the last 3 months showing the registered business address.', false),
};

const BUSINESS_TYPE_FIELD = field('business_type', 'Business Structure', 'select', true, {
  options: ['private_company', 'public_company', 'sole_proprietor', 'partnership', 'ngo', 'trust', 'other'],
  placeholder: 'Select business structure',
});

const LEGAL_NAME_FIELD = field('legal_name', 'Legal Company Name', 'text', true, {
  placeholder: 'Exact name as registered',
});

const INCORPORATION_DATE_FIELD = field('incorporation_date', 'Date of Incorporation', 'date', false);

export const KYB_COUNTRY_CONFIGS: CountryKybConfig[] = [
  // ─── AFRICA ──────────────────────────────────────────────────────────────────
  {
    countryCode: 'ZA',
    countryName: 'South Africa',
    currency: 'ZAR',
    registrationAuthority: 'CIPC (Companies and Intellectual Property Commission)',
    documents: [
      doc('cipc_certificate', 'CIPC Certificate of Incorporation', 'Certificate issued by the Companies and Intellectual Property Commission confirming business registration.'),
      doc('tax_clearance', 'SARS Tax Clearance / Good Standing Letter', 'Current tax clearance certificate or letter of good standing from the South African Revenue Service.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('registration_number', 'CIPC Registration Number', 'text', true, { placeholder: 'e.g. 2021/123456/07' }),
      field('tax_number', 'SARS Income Tax Number', 'text', true, { placeholder: 'e.g. 9123456789' }),
      field('vat_number', 'VAT Registration Number', 'text', false, { placeholder: 'e.g. 4123456789' }),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'NG',
    countryName: 'Nigeria',
    currency: 'NGN',
    registrationAuthority: 'CAC (Corporate Affairs Commission)',
    documents: [
      doc('cac_certificate', 'CAC Certificate of Incorporation', 'Certificate of Incorporation issued by the Corporate Affairs Commission.'),
      doc('cac_form7', 'CAC Form 7 — Particulars of Directors', 'Certified copy of CAC Form 7 listing all company directors.'),
      doc('tin_certificate', 'FIRS TIN Certificate', 'Tax Identification Number certificate from the Federal Inland Revenue Service.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('rc_number', 'CAC RC Number', 'text', true, { placeholder: 'e.g. RC-1234567' }),
      field('tin', 'FIRS Tax Identification Number (TIN)', 'text', true, { placeholder: 'e.g. 12345678-0001' }),
      field('registered_address', 'Registered Office Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'KE',
    countryName: 'Kenya',
    currency: 'KES',
    registrationAuthority: 'Registrar of Companies (Office of the Attorney General)',
    documents: [
      doc('reg_certificate', 'Certificate of Registration / Incorporation', 'Certificate issued by the Registrar of Companies.'),
      doc('kra_pin', 'KRA PIN Certificate (Company)', 'Business PIN certificate issued by the Kenya Revenue Authority.'),
      COMMON_DOCS.directorId,
      doc('business_permit', 'Single Business Permit / County Licence', 'Current business operating permit from the relevant county government.', false),
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('reg_number', 'Business Registration Number', 'text', true, { placeholder: 'e.g. PVT-A12345' }),
      field('kra_pin', 'KRA PIN (Company)', 'text', true, { placeholder: 'e.g. P051234567A' }),
      field('director_kra_pin', "Director's KRA PIN", 'text', false),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'GH',
    countryName: 'Ghana',
    currency: 'GHS',
    registrationAuthority: "Registrar General's Department",
    documents: [
      doc('rgd_certificate', 'RGD Certificate of Incorporation', "Certificate of Incorporation from the Registrar General's Department."),
      doc('tin_certificate', 'GRA TIN Certificate', 'Tax Identification Number certificate from the Ghana Revenue Authority.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('reg_number', 'Company Registration Number', 'text', true, { placeholder: 'e.g. CS-012345' }),
      field('tin', 'GRA Tax Identification Number (TIN)', 'text', true),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'TZ',
    countryName: 'Tanzania',
    currency: 'TZS',
    registrationAuthority: 'BRELA (Business Registrations and Licensing Agency)',
    documents: [
      doc('brela_certificate', 'BRELA Certificate of Incorporation', 'Certificate of Incorporation from the Business Registrations and Licensing Agency.'),
      doc('tin_certificate', 'TRA TIN Certificate', 'Tax Identification Number certificate from the Tanzania Revenue Authority.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('reg_number', 'Company Registration Number', 'text', true),
      field('tin', 'TRA Tax Identification Number', 'text', true),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'EG',
    countryName: 'Egypt',
    currency: 'EGP',
    registrationAuthority: 'GAFI (General Authority for Investment and Free Zones)',
    documents: [
      doc('commercial_registry', 'Commercial Registry Certificate', 'Extract from the Egyptian Commercial Registry confirming business registration.'),
      doc('tax_card', 'Tax Registration Card', 'Tax card issued by the Egyptian Tax Authority.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('commercial_reg_number', 'Commercial Registry Number', 'text', true),
      field('tax_card_number', 'Tax Card Number', 'text', true),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'MA',
    countryName: 'Morocco',
    currency: 'MAD',
    registrationAuthority: 'Registre du Commerce (OMPIC)',
    documents: [
      doc('rc_certificate', 'Registre du Commerce Extract (RC)', 'Current extract from the Registre du Commerce.'),
      doc('tax_id_certificate', 'Identifiant Fiscal Certificate', 'Certificate of fiscal identification issued by the tax authority (DGI).'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('rc_number', 'RC Number (Numéro du Registre du Commerce)', 'text', true),
      field('if_number', 'Identifiant Fiscal (IF)', 'text', true),
      field('ice_number', "ICE Number (Identifiant Commun de l'Entreprise)", 'text', false),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'ZW',
    countryName: 'Zimbabwe',
    currency: 'ZWL',
    registrationAuthority: 'Companies and Other Business Entities Office (COBEO)',
    documents: [
      doc('cobeo_certificate', 'Certificate of Incorporation (COBEO)', 'Certificate of Incorporation from the Companies and Other Business Entities Office.'),
      doc('zimra_certificate', 'ZIMRA Business Partner Number', 'Tax registration certificate from the Zimbabwe Revenue Authority.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('reg_number', 'Company Registration Number', 'text', true),
      field('tin', 'ZIMRA Business Partner Number (BPN)', 'text', true),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'ET',
    countryName: 'Ethiopia',
    currency: 'ETB',
    registrationAuthority: 'Ministry of Trade and Regional Integration',
    documents: [
      doc('trade_license', 'Commercial Registration / Trade Licence', 'Commercial registration or trade licence issued by the Ministry of Trade.'),
      doc('tin_certificate', 'TIN Certificate (ERCA)', 'Tax Identification Number certificate from the Ethiopian Revenue and Customs Authority.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('trade_license_number', 'Trade Licence Number', 'text', true),
      field('tin', 'ERCA Tax Identification Number (TIN)', 'text', true),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'SN',
    countryName: 'Senegal',
    currency: 'XOF',
    registrationAuthority: 'APIX / RCCM (Registre du Commerce et du Crédit Mobilier)',
    documents: [
      doc('rccm_certificate', 'RCCM Registration Certificate', 'Certificate from the Registre du Commerce et du Crédit Mobilier.'),
      doc('ninea_certificate', 'NINEA Certificate', "Numéro d'Identification National des Entreprises et Associations."),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('rccm_number', 'RCCM Registration Number', 'text', true),
      field('ninea', 'NINEA Number', 'text', true),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'UG',
    countryName: 'Uganda',
    currency: 'UGX',
    registrationAuthority: 'URSB (Uganda Registration Services Bureau)',
    documents: [
      doc('ursb_certificate', 'URSB Certificate of Incorporation', 'Certificate of Incorporation from the Uganda Registration Services Bureau.'),
      doc('tin_certificate', 'URA TIN Certificate', 'Tax Identification Number from the Uganda Revenue Authority.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('reg_number', 'Company Registration Number', 'text', true),
      field('tin', 'URA Tax Identification Number (TIN)', 'text', true),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'RW',
    countryName: 'Rwanda',
    currency: 'RWF',
    registrationAuthority: 'RDB (Rwanda Development Board)',
    documents: [
      doc('rdb_certificate', 'RDB Certificate of Incorporation', 'Certificate of Incorporation from the Rwanda Development Board.'),
      doc('tin_certificate', 'RRA TIN Certificate', 'Tax Identification Number from the Rwanda Revenue Authority.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('reg_number', 'Company Registration Number', 'text', true),
      field('tin', 'RRA Tax Identification Number (TIN)', 'text', true),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },

  // ─── NORTH AMERICA ────────────────────────────────────────────────────────────
  {
    countryCode: 'US',
    countryName: 'United States',
    currency: 'USD',
    registrationAuthority: 'Secretary of State (state-level) + IRS (federal)',
    documents: [
      doc('articles_of_incorporation', 'Articles of Incorporation / Certificate of Formation', 'State-issued certificate of incorporation, articles of organization, or certificate of formation.'),
      doc('ein_letter', 'IRS EIN Assignment Letter (CP-575)', 'IRS letter confirming your Employer Identification Number (EIN).'),
      doc('operating_agreement', 'Operating Agreement / Corporate Bylaws', 'Internal governance document (operating agreement for LLCs, bylaws for corporations).', false),
      doc('beneficial_owner_id', 'Beneficial Owner ID (≥25% ownership)', "Government-issued photo ID for each individual owning 25% or more of the business."),
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('ein', 'Employer Identification Number (EIN)', 'text', true, { placeholder: 'e.g. 12-3456789' }),
      field('state_of_incorporation', 'State of Incorporation / Formation', 'text', true, { placeholder: 'e.g. Delaware' }),
      field('registered_address', 'Principal Business Address', 'text', true),
      field('director_name', 'Responsible Party / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
    notes: 'Beneficial Ownership Certification required per FinCEN rules for LLCs and corporations.',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    currency: 'CAD',
    registrationAuthority: 'Corporations Canada (federal) or Provincial Registry',
    documents: [
      doc('cert_of_incorporation', 'Certificate of Incorporation', 'Federal (Corporations Canada) or provincial certificate of incorporation.'),
      doc('cra_bn_letter', 'CRA Business Number (BN) Confirmation', 'Letter from the Canada Revenue Agency confirming the Business Number.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('corporation_number', 'Corporation Number', 'text', true),
      field('cra_bn', 'CRA Business Number (BN)', 'text', true, { placeholder: 'e.g. 123456789 RT0001' }),
      field('province_of_incorporation', 'Province / Territory of Incorporation', 'text', true),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    currency: 'MXN',
    registrationAuthority: 'Registro Público de Comercio (via SAT)',
    documents: [
      doc('acta_constitutiva', 'Acta Constitutiva', 'Notarised deed of incorporation (acta constitutiva).'),
      doc('rfc_certificate', 'RFC Certificate (SAT)', 'Registro Federal de Contribuyentes certificate from the SAT.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('rfc', 'RFC (Registro Federal de Contribuyentes)', 'text', true, { placeholder: 'e.g. ABC123456XYZ' }),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },

  // ─── EUROPE ───────────────────────────────────────────────────────────────────
  {
    countryCode: 'GB',
    countryName: 'United Kingdom',
    currency: 'GBP',
    registrationAuthority: 'Companies House',
    documents: [
      doc('companies_house_cert', 'Companies House Certificate of Incorporation', 'Certificate of Incorporation issued by Companies House.'),
      doc('articles_of_association', 'Memorandum & Articles of Association', 'Signed memorandum and articles of association.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('companies_house_number', 'Companies House Number', 'text', true, { placeholder: 'e.g. 12345678' }),
      field('utr', 'HMRC Unique Taxpayer Reference (UTR)', 'text', false, { placeholder: 'e.g. 1234567890' }),
      field('vat_number', 'VAT Registration Number', 'text', false, { placeholder: 'e.g. GB123456789' }),
      field('registered_address', 'Registered Office Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'DE',
    countryName: 'Germany',
    currency: 'EUR',
    registrationAuthority: 'Handelsregister (Commercial Register)',
    documents: [
      doc('handelsregister', 'Handelsregisterauszug (Commercial Register Extract)', 'Certified extract from the Handelsregister (HRB or HRA).'),
      doc('gesellschaftsvertrag', 'Gesellschaftsvertrag (Articles of Association)', 'Notarised articles of association (Gesellschaftsvertrag).'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('hrb_number', 'Handelsregister Number (HRB/HRA)', 'text', true, { placeholder: 'e.g. HRB 123456' }),
      field('steuernummer', 'Steuernummer (Tax ID)', 'text', true),
      field('ust_id', 'Umsatzsteuer-ID (VAT)', 'text', false, { placeholder: 'e.g. DE123456789' }),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Geschäftsführer / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'FR',
    countryName: 'France',
    currency: 'EUR',
    registrationAuthority: 'Greffe du Tribunal de Commerce (via INPI)',
    documents: [
      doc('kbis', 'Extrait Kbis', "Official Kbis extract from the Registre du Commerce et des Sociétés (no older than 3 months)."),
      doc('statuts', 'Statuts de la Société', 'Signed and registered company statutes.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('siren', 'SIREN Number', 'text', true, { placeholder: 'e.g. 123 456 789' }),
      field('siret', 'SIRET Number', 'text', true, { placeholder: 'e.g. 123 456 789 00012' }),
      field('vat_number', 'Numéro de TVA Intracommunautaire', 'text', false, { placeholder: 'e.g. FR12345678901' }),
      field('registered_address', 'Siège Social Address', 'text', true),
      field('director_name', 'Gérant / Président / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'IT',
    countryName: 'Italy',
    currency: 'EUR',
    registrationAuthority: 'Camera di Commercio (CCIAA)',
    documents: [
      doc('visura_camerale', 'Visura Camerale (Chamber of Commerce Extract)', 'Current visura camerale extract (no older than 3 months).'),
      doc('atto_costitutivo', 'Atto Costitutivo (Deed of Incorporation)', 'Notarised deed of incorporation.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('codice_fiscale', 'Codice Fiscale (Tax Code)', 'text', true),
      field('partita_iva', 'Partita IVA (VAT Number)', 'text', true, { placeholder: 'e.g. IT12345678901' }),
      field('rea_number', 'REA Number (Camera di Commercio)', 'text', true),
      field('registered_address', 'Sede Legale Address', 'text', true),
      field('director_name', 'Rappresentante Legale / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'ES',
    countryName: 'Spain',
    currency: 'EUR',
    registrationAuthority: 'Registro Mercantil',
    documents: [
      doc('registro_mercantil', 'Nota Simple del Registro Mercantil', 'Current nota simple from the Registro Mercantil (no older than 3 months).'),
      doc('escritura', 'Escritura de Constitución', 'Notarised deed of incorporation.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('cif', 'CIF / NIF de la Sociedad', 'text', true, { placeholder: 'e.g. B12345678' }),
      field('registered_address', 'Domicilio Social Address', 'text', true),
      field('director_name', 'Administrador / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'NL',
    countryName: 'Netherlands',
    currency: 'EUR',
    registrationAuthority: 'KvK (Kamer van Koophandel)',
    documents: [
      doc('kvk_extract', 'KvK Extract (Chamber of Commerce)', 'Current extract from the KvK (Kamer van Koophandel) — no older than 3 months.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('kvk_number', 'KvK Number', 'text', true, { placeholder: 'e.g. 12345678' }),
      field('btw_number', 'BTW Number (VAT)', 'text', false, { placeholder: 'e.g. NL123456789B01' }),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'PT',
    countryName: 'Portugal',
    currency: 'EUR',
    registrationAuthority: 'IRN (Instituto dos Registos e do Notariado)',
    documents: [
      doc('cert_of_registration', 'Certidão Permanente (Permanent Certificate)', 'Permanent certificate of commercial registration from the IRN.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('nipc', 'NIPC (Número de Identificação de Pessoa Colectiva)', 'text', true, { placeholder: 'e.g. 500123456' }),
      field('nif', 'NIF (Número de Identificação Fiscal)', 'text', false),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Gerente / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'IE',
    countryName: 'Ireland',
    currency: 'EUR',
    registrationAuthority: 'CRO (Companies Registration Office)',
    documents: [
      doc('cro_certificate', 'CRO Certificate of Incorporation', 'Certificate of Incorporation from the Companies Registration Office.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('cro_number', 'CRO Number', 'text', true, { placeholder: 'e.g. 123456' }),
      field('tax_reg_number', 'Revenue Tax Registration Number', 'text', false),
      field('vat_number', 'VAT Registration Number', 'text', false, { placeholder: 'e.g. IE1234567T' }),
      field('registered_address', 'Registered Office Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'PL',
    countryName: 'Poland',
    currency: 'PLN',
    registrationAuthority: 'KRS (Krajowy Rejestr Sądowy)',
    documents: [
      doc('krs_extract', 'KRS Extract (National Court Register)', 'Current extract from the Krajowy Rejestr Sądowy.'),
      doc('nip_certificate', 'NIP Certificate (Tax ID)', 'NIP (Numer Identyfikacji Podatkowej) certificate.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('krs_number', 'KRS Number', 'text', true),
      field('nip', 'NIP (Tax Identification Number)', 'text', true),
      field('regon', 'REGON Number (Statistical Number)', 'text', true),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Prezes / Director / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'SE',
    countryName: 'Sweden',
    currency: 'SEK',
    registrationAuthority: 'Bolagsverket (Swedish Companies Registration Office)',
    documents: [
      doc('bolagsverket_cert', 'Bolagsverket Registration Certificate', 'Certificate or extract from Bolagsverket.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('org_number', 'Organisationsnummer (Org. Nr.)', 'text', true, { placeholder: 'e.g. 556000-0000' }),
      field('vat_number', 'VAT Number (Momsregistreringsnummer)', 'text', false, { placeholder: 'e.g. SE556000000001' }),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'VD / Styrelseledamot / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'NO',
    countryName: 'Norway',
    currency: 'NOK',
    registrationAuthority: 'Brønnøysundregistrene (Brønnøysund Register Centre)',
    documents: [
      doc('brreg_certificate', 'Brønnøysund Registration Certificate', 'Certificate of registration from the Brønnøysund Register Centre.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('org_number', 'Organisasjonsnummer', 'text', true, { placeholder: 'e.g. 123 456 789' }),
      field('mva_number', 'MVA Number (VAT)', 'text', false),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Daglig leder / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'DK',
    countryName: 'Denmark',
    currency: 'DKK',
    registrationAuthority: 'Erhvervsstyrelsen (Danish Business Authority)',
    documents: [
      doc('cvr_extract', 'CVR Extract (Central Business Register)', 'Current extract from the Danish CVR (Centrale Virksomhedsregister).'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('cvr_number', 'CVR Number', 'text', true, { placeholder: 'e.g. 12345678' }),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Direktør / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'FI',
    countryName: 'Finland',
    currency: 'EUR',
    registrationAuthority: 'PRH (Patent and Registration Office)',
    documents: [
      doc('prh_certificate', 'PRH Trade Register Certificate', 'Certificate of registration from the Finnish Patent and Registration Office.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('y_tunnus', 'Y-tunnus (Business ID)', 'text', true, { placeholder: 'e.g. 1234567-8' }),
      field('vat_number', 'ALV-numero (VAT)', 'text', false, { placeholder: 'e.g. FI12345678' }),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Toimitusjohtaja / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'CH',
    countryName: 'Switzerland',
    currency: 'CHF',
    registrationAuthority: 'Handelsregisteramt (Commercial Register Office)',
    documents: [
      doc('hr_extract', 'Handelsregisterauszug (Commercial Register Extract)', 'Current extract from the cantonal Handelsregister.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('che_number', 'CHE Number (UID)', 'text', true, { placeholder: 'e.g. CHE-123.456.789' }),
      field('mwst_number', 'MWST/TVA/IVA Number (VAT)', 'text', false),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Geschäftsführer / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'AT',
    countryName: 'Austria',
    currency: 'EUR',
    registrationAuthority: 'Firmenbuch (Austrian Commercial Register)',
    documents: [
      doc('firmenbuch_extract', 'Firmenbuchauszug (Commercial Register Extract)', 'Current extract from the Firmenbuch.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('fn_number', 'Firmenbuchnummer (FN)', 'text', true, { placeholder: 'e.g. FN 123456a' }),
      field('uid_number', 'UID (Umsatzsteuer-Identifikationsnummer)', 'text', false, { placeholder: 'e.g. ATU12345678' }),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Geschäftsführer / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'BE',
    countryName: 'Belgium',
    currency: 'EUR',
    registrationAuthority: 'BCE/KBO (Banque-Carrefour des Entreprises)',
    documents: [
      doc('bce_extract', 'BCE/KBO Extract', 'Current extract from the Banque-Carrefour des Entreprises.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('bce_number', 'BCE/KBO Number', 'text', true, { placeholder: 'e.g. BE 0123.456.789' }),
      field('vat_number', 'BTW/TVA Number (VAT)', 'text', false, { placeholder: 'e.g. BE0123456789' }),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Administrateur / Gérant / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },

  // ─── MIDDLE EAST ──────────────────────────────────────────────────────────────
  {
    countryCode: 'AE',
    countryName: 'United Arab Emirates',
    currency: 'AED',
    registrationAuthority: 'DED / ADGM / DIFC / Free Zone Authority',
    documents: [
      doc('trade_license', 'UAE Trade Licence', 'Current trade licence issued by the relevant licensing authority (DED, free zone, or offshore authority).'),
      doc('moa', 'Memorandum of Association (MOA)', 'Notarised MOA from the relevant authority.'),
      doc('establishment_card', 'Establishment Card', 'Establishment card / immigration card for the company.', false),
      COMMON_DOCS.directorId,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('trade_license_number', 'Trade Licence Number', 'text', true),
      field('licensing_authority', 'Licensing Authority / Emirate', 'text', true, { placeholder: 'e.g. DED Dubai, RAKEZ, ADGM' }),
      field('activity_code', 'Business Activity Code', 'text', false),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Manager / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'SA',
    countryName: 'Saudi Arabia',
    currency: 'SAR',
    registrationAuthority: 'Ministry of Commerce (MoC) — MISA for foreign entities',
    documents: [
      doc('commercial_register', 'Commercial Register (السجل التجاري)', 'Commercial register certificate issued by the Ministry of Commerce.'),
      doc('zatca_vat_cert', 'ZATCA VAT Certificate', 'VAT registration certificate from the Zakat, Tax and Customs Authority.', false),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('cr_number', 'CR Number (رقم السجل التجاري)', 'text', true),
      field('vat_number', 'VAT Number', 'text', false),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Manager / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'QA',
    countryName: 'Qatar',
    currency: 'QAR',
    registrationAuthority: 'Ministry of Commerce and Industry (MoCI)',
    documents: [
      doc('commercial_register', 'Commercial Registration Certificate', 'Commercial registration certificate from MoCI or the relevant free zone authority.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('cr_number', 'Commercial Registration Number', 'text', true),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Manager / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'KW',
    countryName: 'Kuwait',
    currency: 'KWD',
    registrationAuthority: 'Ministry of Commerce and Industry (MOCI)',
    documents: [
      doc('commercial_register', 'Commercial Registry Certificate', 'Commercial registry certificate from MOCI.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('cr_number', 'Commercial Registration Number', 'text', true),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Manager / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'BH',
    countryName: 'Bahrain',
    currency: 'BHD',
    registrationAuthority: 'MOICT (Ministry of Industry, Commerce and Tourism)',
    documents: [
      doc('cr_certificate', 'Commercial Registration Certificate', 'CR certificate from MOICT.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('cr_number', 'CR Number', 'text', true),
      field('vat_number', 'VAT Registration Number', 'text', false),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Manager / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'OM',
    countryName: 'Oman',
    currency: 'OMR',
    registrationAuthority: 'Ministry of Commerce, Industry and Investment Promotion',
    documents: [
      doc('cr_certificate', 'Commercial Registration Certificate', 'Commercial registration certificate from the Ministry of Commerce.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('cr_number', 'Commercial Registration Number', 'text', true),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Manager / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'JO',
    countryName: 'Jordan',
    currency: 'JOD',
    registrationAuthority: 'Companies Controller Directorate (Ministry of Industry & Trade)',
    documents: [
      doc('cr_certificate', 'Commercial Registration Certificate', 'CR certificate from the Companies Controller Directorate.'),
      doc('tin_certificate', 'Income Tax Department Registration', 'Tax registration certificate from the Income and Sales Tax Department.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('cr_number', 'Commercial Registration Number', 'text', true),
      field('tin', 'Tax Registration Number', 'text', true),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Manager / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },

  // ─── ASIA ─────────────────────────────────────────────────────────────────────
  {
    countryCode: 'IN',
    countryName: 'India',
    currency: 'INR',
    registrationAuthority: 'MCA (Ministry of Corporate Affairs)',
    documents: [
      doc('mca_certificate', 'MCA Certificate of Incorporation', 'Certificate of Incorporation issued by the MCA (with CIN).'),
      doc('pan_card', 'PAN Card (Company)', 'Permanent Account Number card for the company.'),
      doc('gst_certificate', 'GST Registration Certificate', 'GST registration certificate (if applicable).', false),
      doc('moa_aoa', 'MOA and AOA', 'Memorandum of Association and Articles of Association.'),
      COMMON_DOCS.directorId,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('cin', 'CIN (Corporate Identity Number)', 'text', true, { placeholder: 'e.g. U12345MH2020PTC123456' }),
      field('pan', 'Company PAN', 'text', true, { placeholder: 'e.g. AABCS1234N' }),
      field('gstin', 'GSTIN (if applicable)', 'text', false, { placeholder: 'e.g. 22AABCS1234N1Z5' }),
      field('registered_address', 'Registered Office Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory', 'text', true),
      field('director_din', 'Director DIN', 'text', false, { placeholder: '8-digit DIN' }),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'CN',
    countryName: 'China',
    currency: 'CNY',
    registrationAuthority: 'SAMR (State Administration for Market Regulation)',
    documents: [
      doc('business_license', '营业执照 (Business Licence)', 'Business licence (营业执照) issued by SAMR showing the Unified Social Credit Code.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('uscc', 'Unified Social Credit Code (统一社会信用代码)', 'text', true, { placeholder: '18-character USCC' }),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('legal_representative', 'Legal Representative (法人代表)', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'JP',
    countryName: 'Japan',
    currency: 'JPY',
    registrationAuthority: 'Legal Affairs Bureau (法務局)',
    documents: [
      doc('touki_cert', '登記事項証明書 (Corporate Registry Certificate)', 'Certificate of registered matters (登記事項証明書) from the Legal Affairs Bureau.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('houjin_number', '法人番号 (Corporate Number)', 'text', true, { placeholder: '13-digit corporate number' }),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('representative_name', '代表取締役 / Representative Director', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'KR',
    countryName: 'South Korea',
    currency: 'KRW',
    registrationAuthority: 'Supreme Court Registry / National Tax Service',
    documents: [
      doc('corp_registry', '법인등기부등본 (Corporate Registry Extract)', 'Corporate registry extract from the Supreme Court Registration Office.'),
      doc('business_reg', '사업자등록증 (Business Registration Certificate)', 'Business registration certificate from the National Tax Service.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('business_reg_number', '사업자등록번호 (Business Registration Number)', 'text', true, { placeholder: 'e.g. 123-45-67890' }),
      field('corp_reg_number', '법인등록번호 (Corporate Registration Number)', 'text', false),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('representative_name', '대표이사 (Representative Director)', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'SG',
    countryName: 'Singapore',
    currency: 'SGD',
    registrationAuthority: 'ACRA (Accounting and Corporate Regulatory Authority)',
    documents: [
      doc('acra_profile', 'ACRA Business Profile', 'Current ACRA business profile extract.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('uen', 'UEN (Unique Entity Number)', 'text', true, { placeholder: 'e.g. 201234567A' }),
      field('gst_number', 'GST Registration Number', 'text', false),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'MY',
    countryName: 'Malaysia',
    currency: 'MYR',
    registrationAuthority: 'SSM (Suruhanjaya Syarikat Malaysia)',
    documents: [
      doc('ssm_certificate', 'SSM Certificate of Incorporation', 'Certificate of Incorporation from Suruhanjaya Syarikat Malaysia (SSM).'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('company_number', 'Company Number (SSM)', 'text', true),
      field('tin', 'Income Tax Reference Number (LHDN)', 'text', false),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'TH',
    countryName: 'Thailand',
    currency: 'THB',
    registrationAuthority: 'DBD (Department of Business Development)',
    documents: [
      doc('dbd_certificate', 'DBD Certificate of Incorporation', 'Certificate of incorporation from the Department of Business Development.'),
      doc('tax_certificate', 'TRD Tax Registration Certificate', 'Tax registration certificate from the Thailand Revenue Department.', false),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('reg_number', 'Company Registration Number', 'text', true),
      field('tax_id', 'Tax Identification Number', 'text', false),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'ID',
    countryName: 'Indonesia',
    currency: 'IDR',
    registrationAuthority: 'OSS (Online Single Submission) — AHU for corporate',
    documents: [
      doc('nib', 'NIB (Nomor Induk Berusaha)', 'Business Identification Number (NIB) from the OSS system.'),
      doc('npwp', 'NPWP Certificate (Tax ID)', 'NPWP (Nomor Pokok Wajib Pajak) certificate from the tax office.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('nib_number', 'NIB Number', 'text', true),
      field('npwp', 'NPWP (Tax ID)', 'text', true),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Direktur / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'PH',
    countryName: 'Philippines',
    currency: 'PHP',
    registrationAuthority: 'SEC (Securities and Exchange Commission) / DTI (for sole proprietors)',
    documents: [
      doc('sec_certificate', 'SEC Certificate of Incorporation', 'Certificate of Incorporation from the SEC (or DTI Certificate for sole proprietors).'),
      doc('bir_certificate', 'BIR Certificate of Registration', 'Certificate of Registration from the Bureau of Internal Revenue (BIR Form 2303).'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('sec_reg_number', 'SEC Registration Number', 'text', true),
      field('bir_tin', 'BIR TIN (Tax Identification Number)', 'text', true),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'President / Director / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'VN',
    countryName: 'Vietnam',
    currency: 'VND',
    registrationAuthority: 'Department of Planning and Investment (DPI)',
    documents: [
      doc('brc', 'Business Registration Certificate (Giấy chứng nhận đăng ký doanh nghiệp)', 'Business registration certificate from the DPI.'),
      doc('tax_reg', 'Tax Registration Certificate', 'Tax registration certificate from the General Department of Taxation.', false),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('enterprise_code', 'Enterprise Code (Mã số doanh nghiệp)', 'text', true),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Legal Representative / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'PK',
    countryName: 'Pakistan',
    currency: 'PKR',
    registrationAuthority: 'SECP (Securities and Exchange Commission of Pakistan)',
    documents: [
      doc('secp_certificate', 'SECP Certificate of Incorporation', 'Certificate of Incorporation from the SECP.'),
      doc('ntn_certificate', 'NTN Certificate (FBR)', 'National Tax Number certificate from the Federal Board of Revenue.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('secp_number', 'SECP Registration Number (CRNC)', 'text', true),
      field('ntn', 'NTN (National Tax Number)', 'text', true),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'BD',
    countryName: 'Bangladesh',
    currency: 'BDT',
    registrationAuthority: 'RJSC (Registrar of Joint Stock Companies and Firms)',
    documents: [
      doc('rjsc_certificate', 'RJSC Certificate of Incorporation', 'Certificate of Incorporation from the RJSC.'),
      doc('tin_certificate', 'TIN Certificate (NBR)', 'Tax Identification Number certificate from the National Board of Revenue.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('reg_number', 'RJSC Registration Number', 'text', true),
      field('tin', 'TIN (Tax Identification Number)', 'text', true),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'LK',
    countryName: 'Sri Lanka',
    currency: 'LKR',
    registrationAuthority: 'Registrar of Companies (ROC)',
    documents: [
      doc('roc_certificate', 'ROC Certificate of Incorporation', 'Certificate of Incorporation from the Registrar of Companies.'),
      doc('tin_certificate', 'TIN Certificate (IRD)', 'Taxpayer Identification Number certificate from the Inland Revenue Department.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('company_number', 'Company Registration Number', 'text', true),
      field('tin', 'TIN (Taxpayer Identification Number)', 'text', true),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },

  // ─── SOUTH AMERICA ────────────────────────────────────────────────────────────
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    currency: 'BRL',
    registrationAuthority: 'JUCESP / JUCERJA (State Commercial Boards) + Receita Federal',
    documents: [
      doc('contrato_social', 'Contrato Social / Estatuto Social', 'Notarised and registered articles of incorporation.'),
      doc('cnpj_certificate', 'CNPJ Certificate (Receita Federal)', 'CNPJ certificate from the Receita Federal do Brasil.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('cnpj', 'CNPJ (Cadastro Nacional da Pessoa Jurídica)', 'text', true, { placeholder: 'e.g. 12.345.678/0001-00' }),
      field('inscricao_estadual', 'Inscrição Estadual (State VAT)', 'text', false),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Sócio-administrador / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'CO',
    countryName: 'Colombia',
    currency: 'COP',
    registrationAuthority: 'Cámara de Comercio',
    documents: [
      doc('camara_cert', 'Cámara de Comercio Certificate', 'Current certificate of existence and legal representation from the Cámara de Comercio (no older than 30 days).'),
      doc('rut', 'RUT (DIAN)', 'Registro Único Tributario from the DIAN.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('nit', 'NIT (Número de Identificación Tributaria)', 'text', true, { placeholder: 'e.g. 900.123.456-7' }),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Representante Legal / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    currency: 'ARS',
    registrationAuthority: 'IGJ (Inspección General de Justicia)',
    documents: [
      doc('estatuto_social', 'Estatuto Social (Articles of Incorporation)', 'Notarised and registered estatuto social.'),
      doc('afip_cuit', 'AFIP CUIT Certificate', 'CUIT registration certificate from the AFIP.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('cuit', 'CUIT (Código Único de Identificación Tributaria)', 'text', true, { placeholder: 'e.g. 30-12345678-9' }),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Director / Autorizado Firmante', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'CL',
    countryName: 'Chile',
    currency: 'CLP',
    registrationAuthority: 'Registro de Comercio (CBR) + SII',
    documents: [
      doc('escritura_pub', 'Escritura Pública de Constitución', 'Notarised deed of incorporation registered at the CBR.'),
      doc('sii_rut', 'SII RUT Certificate', 'RUT (Rol Único Tributario) certificate from the SII.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('rut', 'RUT (Rol Único Tributario)', 'text', true, { placeholder: 'e.g. 76.123.456-7' }),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Representante Legal / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'PE',
    countryName: 'Peru',
    currency: 'PEN',
    registrationAuthority: 'SUNARP (Superintendencia Nacional de los Registros Públicos)',
    documents: [
      doc('sunarp_cert', 'SUNARP Certificate of Existence', 'Current certificate of existence and legal representation from SUNARP.'),
      doc('sunat_ruc', 'SUNAT RUC Certificate', 'RUC (Registro Único de Contribuyentes) certificate from SUNAT.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('ruc', 'RUC (Registro Único de Contribuyentes)', 'text', true, { placeholder: 'e.g. 20123456789' }),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Representante Legal / Authorised Signatory', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },

  // ─── OCEANIA ─────────────────────────────────────────────────────────────────
  {
    countryCode: 'AU',
    countryName: 'Australia',
    currency: 'AUD',
    registrationAuthority: 'ASIC (Australian Securities and Investments Commission)',
    documents: [
      doc('asic_certificate', 'ASIC Certificate of Registration', 'Certificate of registration from ASIC.'),
      doc('abn_registration', 'ABN Registration Confirmation', 'Australian Business Number registration confirmation from the ATO or ABR.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('abn', 'ABN (Australian Business Number)', 'text', true, { placeholder: 'e.g. 12 345 678 901' }),
      field('acn', 'ACN (Australian Company Number)', 'text', false, { placeholder: 'e.g. 123 456 789' }),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
  {
    countryCode: 'NZ',
    countryName: 'New Zealand',
    currency: 'NZD',
    registrationAuthority: 'Companies Office (Ministry of Business, Innovation and Employment)',
    documents: [
      doc('companies_office_cert', 'Companies Office Certificate of Incorporation', 'Certificate of Incorporation from the New Zealand Companies Office.'),
      doc('ird_number', 'IRD Number Confirmation', 'IRD number confirmation from Inland Revenue.'),
      COMMON_DOCS.directorId,
      COMMON_DOCS.proofOfAddress,
    ],
    businessInfoFields: [
      LEGAL_NAME_FIELD,
      BUSINESS_TYPE_FIELD,
      field('company_number', 'Company Number', 'text', true),
      field('nzbn', 'NZBN (New Zealand Business Number)', 'text', false),
      field('ird_number', 'IRD Number', 'text', true),
      field('registered_address', 'Registered Business Address', 'text', true),
      field('director_name', 'Director / Authorised Signatory Name', 'text', true),
      INCORPORATION_DATE_FIELD,
    ],
  },
];

const configMap = new Map<string, CountryKybConfig>(
  KYB_COUNTRY_CONFIGS.map((c) => [c.countryCode.toUpperCase(), c]),
);

export function getCountryKybConfig(countryCode: string): CountryKybConfig | undefined {
  return configMap.get(countryCode.toUpperCase());
}

export function getAllSupportedCountries(): { countryCode: string; countryName: string; currency: string }[] {
  return KYB_COUNTRY_CONFIGS.map(({ countryCode, countryName, currency }) => ({
    countryCode,
    countryName,
    currency,
  }));
}
